// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKFZBVg_kbOfzjWkMOoLKiq_dMmv33de4',
    appId: '1:582383892976:web:e6810225fed3338ca14535',
    messagingSenderId: '582383892976',
    projectId: 'my-flutter-personal-notes',
    authDomain: 'my-flutter-personal-notes.firebaseapp.com',
    storageBucket: 'my-flutter-personal-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtnWSFo7g3_8ovRtYjT5F7BUCJJxJ1Bg8',
    appId: '1:582383892976:android:53449b69ecb1ad86a14535',
    messagingSenderId: '582383892976',
    projectId: 'my-flutter-personal-notes',
    storageBucket: 'my-flutter-personal-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj6dwqUbibKYEZGfdkQREFJV6uq87_HRs',
    appId: '1:582383892976:ios:0c40b211d82a8f94a14535',
    messagingSenderId: '582383892976',
    projectId: 'my-flutter-personal-notes',
    storageBucket: 'my-flutter-personal-notes.appspot.com',
    iosClientId: '582383892976-lih7m701v2n0s7cnb7a4dmmorijo0tb9.apps.googleusercontent.com',
    iosBundleId: 'ke.co.e-skuli.mypersonalnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj6dwqUbibKYEZGfdkQREFJV6uq87_HRs',
    appId: '1:582383892976:ios:0c40b211d82a8f94a14535',
    messagingSenderId: '582383892976',
    projectId: 'my-flutter-personal-notes',
    storageBucket: 'my-flutter-personal-notes.appspot.com',
    iosClientId: '582383892976-lih7m701v2n0s7cnb7a4dmmorijo0tb9.apps.googleusercontent.com',
    iosBundleId: 'ke.co.e-skuli.mypersonalnotes',
  );
}
